name = "stock-ai"
main = "src/server/index.ts"
compatibility_date = "2025-01-01"

[[routes]]
pattern = "stock-ai.uk"
custom_domain = true

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "stock-ai"
database_id = "a40fd260-c66d-433d-9739-2e8222304033"
migrations_dir = "drizzle"
